---
language: ruby
sudo: false
cache: bundler
before_install:
  - gem update bundler
script:
  - bundle exec rubocop
  - bundle exec rake spec
rvm:
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.5.0
  - 2.5.1
  - 2.6.1
